# Generated by Django 3.1.6 on 2021-03-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newuser', '0002_auto_20210321_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
